# Generated by Django 3.1.2 on 2020-10-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('user_email', models.EmailField(max_length=50, unique=True, verbose_name='Email address')),
                ('user_fname', models.CharField(max_length=50, verbose_name='First name')),
                ('user_lname', models.CharField(max_length=50, verbose_name='Last name')),
                ('user_phone', models.CharField(max_length=20, verbose_name='Mobile number')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Date Joined')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff status')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superuser status')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
