# Generated by Django 3.1.2 on 2020-10-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(verbose_name='Room Number')),
                ('room_type', models.CharField(choices=[('STA', 'Standard'), ('DEL', 'Delux')], max_length=3, verbose_name='Type')),
                ('room_bed', models.IntegerField(verbose_name='Number of Bed(s)')),
                ('room_capacity', models.IntegerField(verbose_name='Capacity')),
                ('room_desc', models.TextField(max_length=400, verbose_name='Description')),
            ],
        ),
    ]
