# Generated by Django 3.1.2 on 2020-11-12 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_auto_20201109_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=50, unique=True, verbose_name='Email address')),
                ('customer_fname', models.CharField(max_length=50, verbose_name='First name')),
                ('customer_lname', models.CharField(max_length=50, verbose_name='Last name')),
                ('customer_phone', models.CharField(max_length=20, unique=True, verbose_name='Mobile number')),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.customer', verbose_name='User'),
        ),
    ]
