# Generated by Django 3.1.2 on 2020-11-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_auto_20201112_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
    ]
