# Generated by Django 3.1.2 on 2020-11-13 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_auto_20201113_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.customer', verbose_name='User'),
        ),
    ]
