# Generated by Django 3.1.2 on 2020-11-16 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_auto_20201113_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
    ]
