# Generated by Django 3.1.2 on 2020-11-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_remove_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='room',
            name='room_price',
            field=models.FloatField(null=True),
        ),
    ]
