# Generated by Django 3.1.2 on 2020-11-18 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0017_auto_20201117_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
